language: c
version: ~> 1.0
sudo: true

cache:
  apt: true
  ccache: true

env:
  global: local=0 PROFILE=default DB=testcpp CLEAR_TEXT=0

import: mariadb-corporation/connector-test-machine:common-build.yml@master

jobs:
  allow_failures:
    - env: srv=build
    - os: osx
    - os: linux
      arch: s390x
      dist: focal
  include:
    - stage: Community
      os: osx
      compiler: clang
      before_script:
        - brew install openssl
        - brew install libiodbc
      name: "osx"
    - os: linux
      arch: s390x
      dist: focal
      env: srv=mariadb v=10.11 local=1
      name: "s390x"

script: ./travis.sh
